version: "3.8"
services:
  camunda:
    container_name: camunda
    restart: on-failure
    image: camunda/camunda-bpm-platform:run-latest
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=postgres:5432
    links:
      - postgres
    ports:
      - 8080:8080
  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres:15.4
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5444:5432